kind = "DojoModel"
class_hash = "0x2ccfe3d90e9094720e0c00172f5c76bd9d71642bd80c098c954d0abf9919450"
original_class_hash = "0x2ccfe3d90e9094720e0c00172f5c76bd9d71642bd80c098c954d0abf9919450"
abi = "manifests/dev/abis/base/models/mancala_models_seed_seed.json"
name = "mancala::models::seed::seed"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "position"
type = "Vec2"
key = true

[[members]]
name = "player_side"
type = "PlayerSide"
key = false
