kind = "DojoModel"
class_hash = "0x26560d64f3017bf49114c68ee8ba7cdedf67a05a8c99605958050c621635ac3"
original_class_hash = "0x26560d64f3017bf49114c68ee8ba7cdedf67a05a8c99605958050c621635ac3"
abi = "manifests/dev/abis/base/models/mancala_models_game_game_turn.json"
name = "mancala::models::game::game_turn"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_side"
type = "PlayerSide"
key = false
