kind = "DojoModel"
class_hash = "0x102f1e9e17bf47bb54354e926f5a81a9076a57d343334c6df1e789d5be1b48b"
original_class_hash = "0x102f1e9e17bf47bb54354e926f5a81a9076a57d343334c6df1e789d5be1b48b"
abi = "manifests/dev/abis/base/models/mancala_models_mancala_game_mancala_game.json"
name = "mancala::models::mancala_game::mancala_game"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player_one"
type = "ContractAddress"
key = false

[[members]]
name = "player_two"
type = "ContractAddress"
key = false

[[members]]
name = "current_player"
type = "ContractAddress"
key = false

[[members]]
name = "last_move"
type = "u64"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "GameStatus"
key = false

[[members]]
name = "is_private"
type = "bool"
key = false
