[package]
cairo-version = "2.5.4"
name = "mancala"
version = "0.6.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate plan && sozo migrate apply && ./scripts/default_auth.sh"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xOkhai"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/mancala/katana"
# Default account for katana with seed = 0
account_address = "0x2bc2070abd0aed2486bf97a9453d551c273aefa6f4e953c293c3425f9980999"
private_key = "0x6b3d1e0a6993197cf065cdf4c6522b6192e0eb7bcafb38b8c8d3725eb5631e9"
world_address = "0x1ee592601cde2eb4147136aadf1f2f07d4519d510e0cd013a4339dd09a1e192"  # Update this line with your world address

[tool.dojo.world]
name = "Mancala"
description = "Mancala is a classic strategy board game reimagined as a decentralized, on-chain experience."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://www.starknet.africa/"

[tool.dojo.world.socials]
x = "https://twitter.com/starknetafrica"
github = "https://github.com/realm-of-ra/mancala"
telegram = "https://t.me/starknetafrica"
