kind = "DojoContract"
class_hash = "0x400b18bf47749db3d53347d538ab22315e9e5a4482eed3ae41817cead43d6a6"
original_class_hash = "0x400b18bf47749db3d53347d538ab22315e9e5a4482eed3ae41817cead43d6a6"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"
