kind = "DojoContract"
class_hash = "0x3abf7ac850e53dbadeebfced28f021fe4ff4b2272bdb065d7aee5eb167a1e96"
original_class_hash = "0x3abf7ac850e53dbadeebfced28f021fe4ff4b2272bdb065d7aee5eb167a1e96"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mancala::systems::actions::actions"
