kind = "DojoContract"
class_hash = "0x4ed17d11302248ee0888d799abf196e8f42c0573d57e2219afa2357669baa4d"
original_class_hash = "0x4ed17d11302248ee0888d799abf196e8f42c0573d57e2219afa2357669baa4d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/mancala_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "mancala::systems::actions::actions"
